<?php defined('SYSPATH') OR die('No direct access allowed.');
/**
 *  Dashboard Controller
 */
class Dash_Controller extends Template_Controller {

	// Set the name of the template to use
	public $template = 'template';

	public function index()
	{
		// In Kohana, all views are loaded and treated as objects.
		$this->template->content = new View('dashboard');
		$this->template->schedule = self::schedule();
		$this->template->downloads = self::downloads();
		$this->template->database = self::database();
		$this->template->tools = self::tools();
		$this->template->filelist = self::filelist();

	}

	//public function __call($method, $arguments)
	//{
		// Disable auto-rendering
		//$this->auto_render = FALSE;

		// By defining a __call method, all pages routed to this controller
		// that result in 404 errors will be handled by this method, instead of
		// being displayed as "Page Not Found" errors.
		//echo 'This text is generated by __call. If you expected the index page, you need to use: dash/index/'.substr(Router::$current_uri, 8);
	//}


	public function schedule() {
		if(request::is_ajax()) $this->template = new View('ajax');
		$v =  new View('schedule');

		$v->todo = array(
				"Download links don't work for archived files",
				"Alternate template",
				"Mobile template",
				"Fix Tools tab",
				);

		//$v->schedule = Doctrine::getTable('Schedule')->findAll()->toArray();
		$v->schedule = Doctrine_Query::create()
			->from('Schedule')
			->where("date >= ?",Sound::last_sunday())
			->limit(8)
			->orderBy('date')
			->execute()
			->toArray();

		if(request::is_ajax()) 
			$this->template->content = $v;
		else
			return $v->render();

	}

	public function downloads($date = NULL) {
		if(request::is_ajax()) $this->template = new View('ajax');
		$v = new View('downloads');

		$snd = new Sound;
		$dates = $snd->retrieve_dates($date);

		$v->dates = $dates;
		$v->mp3s = glob('recordings/'.$dates[0].'*.mp3');
		$v->mp3s = array_merge($v->mp3s, glob('recordings/Older/'.$dates[0].'*.mp3'));

		if(request::is_ajax()) 
			$this->template->content = $v;
		else
			return $v->render();
	}

	public function database() {
		if(request::is_ajax()) $this->template = new View('ajax');

		$v = new View('database');
		$v->last_sunday = Sound::last_sunday();
		//$v->data = Doctrine::getTable('Sermons')->findOneByDql("date = ? AND type= ?", array($v->last_sunday, 'sermon'));
		$v->sermon = Doctrine_Query::create()
			->from('Sermons')
			->where("date = ? AND type= ?", array($v->last_sunday, 'Sermons'))
			->execute()
			->getFirst();

		$v->ace = Doctrine_Query::create()
			->from('Aces')
			->where("date = ?", $v->last_sunday)
			->execute()
			->getFirst();

		$v->portrait = Doctrine_Query::create()
			->from('Portraits')
			->where("date = ?", $v->last_sunday)
			->execute()
			->getFirst();

		$v->dedication = Doctrine_Query::create()
			->from('Dedications')
			->where("date = ?", $v->last_sunday)
			->execute()
			->getFirst();

		if(request::is_ajax()) 
			$this->template->content = $v;
		else
			return $v->render();
	}

	public function tools($date = null) {
		if(request::is_ajax()) $this->template = new View('ajax');
		$v = new View('tools');

		$snd = new Sound;
		$dates = $snd->retrieve_dates($date);

		$v->dates = $dates;
		$v->mp3s = glob('/var/www/ctk/'.$dates[0].'*.mp3');
		$v->mp3s = array_merge($v->mp3s, glob('/var/www/ctk/Older/'.$dates[0].'*.mp3'));
		$v->labels = glob("/var/www/sound/webroot/labels/".$dates[0]."*.labels");
		$v->originals = glob("/var/www/sound/webroot/Originals/".$dates[0]."*.flac");

		if(request::is_ajax()) 
			$this->template->content = $v;
		else
			return $v->render();
	}

	public function filelist($date = null) {
		if(request::is_ajax()) $this->template = new View('ajax');
		$v = new View('filelist');

		//$snd = new Sound;
		//$v->dates = $snd->retrieve_dates($date);
		$v->dates = Doctrine_Query::create()
			->from('Sermons')
			->orderBy('date desc')
			->limit(9)
			->execute();

		if(request::is_ajax()) 
			$this->template->content = $v;
		else
			return $v->render();
	}

	public function upload() {
		var_dump($_POST);
	}

	public function autocomplete() {
		if(request::is_ajax())
			$this->template = new View('ajax');
		else
			die('Invalid request.');

		extract($_REQUEST);

		if($val == 'book') {
			$this->_search_books($q);
			die();
		}

		$values = Doctrine_Query::create()
			->select($val)
			->from($type)
			//->where("{$val} LIKE '{$q}%'")
			->where($val.' LIKE ?', $q.'%')
			//->orderBy($val)
			//->limit($limit)
			->execute();

		foreach($values->toArray() as $value) {
			$new[] = $value[$val];
		}

		if(!$new) exit();
		$values = array_unique($new);

		echo implode("\n", $values); exit();
	}

	function _search_books($q) {
			$ot = array(
					'Genesis', 'Exodus', 'Leviticus', 'Numbers', 'Deuteronomy',
					'Joshua', 'Judges', 'Ruth',
					'1 Samuel', '2 Samuel',
					'1 Kings', '2 Kings',
					'1 Chronicles', '2 Chronicles',
					'Ezra', 'Nehemiah',
			//		'Tobit', 'Judith',
					'Esther',
			//		'1 Maccabees', '2 Maccabees',
					'Job',
					'Psalms', 'Proverbs', 'Ecclesiastes', 'Song of Songs',
			//		'Wisdom', 'Sirach',
					'Isaiah', 'Jeremiah', 'Lamentations',
			//		'Baruch',
					'Ezekiel', 'Daniel',
					'Hosea', 'Joel', 'Amos', 'Obadiah',
					'Jonah',
					'Micah', 'Nahum', 'Habakkuk', 'Zephaniah', 'Haggai', 'Zechariah', 'Malachi'
			);

			$nt = array(
					'Matthew', 'Mark', 'Luke', 'John',
					'Acts', 'Romans',
					'1 Corinthians', '2 Corinthians',
					'Galatians', 'Ephesians', 'Philippians', 'Colossians',
					'1 Thessalonians', '2 Thessalonians',
					'1 Timothy', '2 Timothy',
					'Titus',
					'Philemon',
					'Hebrews',
					'James',
					'1 Peter', '2 Peter',
					'1 John', '2 John', '3 John',
					'Jude',
					'Revelation'
			);

		foreach(array_merge($ot,$nt) as $book)
			if(stripos($book,$q) !== FALSE) echo $book."\n";

	}


	public function write_record() {
		if(request::is_ajax()) $this->template = new View('ajax');
		else die('Invalid request.');

		// Sermon: series, title, preacher, scripture, reader, date, disk, type
		// Aces: series, title, teacher, comment, date, disk
		// Portraits: date, speaker, comment, notice_sent
		// Dedications: official, child, comment, notice_sent

		$record = Doctrine_Query::create()
			->from($_REQUEST['type'])
			//->where('type = ? AND date = ?', array($_REQUEST['type'],$_REQUEST['date']))
			->where('date = ?', $_REQUEST['date'])
			->orderBy('id desc')
			->execute()
			->getFirst();

		if(!$record) {
			$record = new $_REQUEST['type'];
			//$record->created_at = date('Y-m-d H:i:s');
			//$record->updated_at = date('Y-m-d H:i:s');
		}

		$record->merge($_REQUEST);
		if(in_array($_REQUEST['type'], array('Sermons','Aces'))) {
			$record->disk = 9;
		}

		if($_REQUEST['type'] == 'Sermons') {
			$record->track = date('W',strtotime($_REQUEST['date']));
			$record->year = date('Y',strtotime($_REQUEST['date']));
		}

		//$record->save();
		if($record->trySave())
			$this->template->content = "Write successful!";
		else
			$this->template->content = "Write failed!";
			//$this->template->content = var_dump(get_class($record));
	}
}
