name: Christ the King Sound Team
description: This is the place to get all recently released Christ the King recordings.
url: http://recordings.ctksound.org/
copyright: Copyright 2001-2014 Christ the King Church of Fox Valley
webmaster: kgust@pobox.com (Kevin Gustavson)
image: images/ctk.gif
markdown: redcarpet
pygments: true
exclude:
    - "*.wav"
    - "*.cue"
    - "*.aup"
    - "*_data"
#lsi: true
