copyright: Copyright 2001-2014 Christ the King Church of Fox Valley
description: This is the place to get all recently released Christ the King recordings.
image: images/ctk.gif
name: Christ the King Sound Team
#permalink: pretty
permalink: /:year/:month/:day
url: http://recordings.ctksound.org/
webmaster: kgust@pobox.com (Kevin Gustavson)

source: ./_source
destination: ./_site

markdown: kramdown
highlighter: pygments
exclude:
    - "*.wav"
    #- "*.flac"
    - "*.cue"
    - "*.aup"
    - "*_data"
    - "iKey_*"
    - "Gemfile"
    - "Rakefile"
    - "/2008"
    - "/2009"
    - "/2010"
    - "/2011"
    - "/2012"
    - "/2013/**/*.flac"
#lsi: true

defaults:
    -
        scope:
            path: "" # empty string means all files
        values:
            layout: default
    -
        scope:
            path: ""
            type: post
        values:
            layout: sunday
