category_dir: ""
copyright: Copyright 2001-2014 Christ the King Church of Fox Valley
description: This is the place to get all recently released Christ the King recordings.
image: images/ctk.gif
#lsi: true
name: Christ the King Sound Team
permalink: /:year/:month/:day
port: 4000
url: http://recordings.ctksound.org/
webmaster: kgust@pobox.com (Kevin Gustavson)

source: ./_source
destination: ./_site

markdown: kramdown
highlighter: pygments
exclude:
  - "*.wav"
  #- "*.flac"
  - "*.cue"
  - "*.m3u"
  - "*.aup"
  - "*_data"
  - "iKey_*"
  - "Gemfile"
  - "Rakefile"
  - "/2008"
  - "/2009"
  - "/2010"
  - "/2011"
  - "/2012"
  - "/2013/**/*.flac"

# Pagination
paginate: 15
pagination_enabled: true
paginate_path: "page-:num"

defaults:
  - scope:
      path: "" # empty string means all files
    values:
      layout: default
  - scope:
      path: ""
      type: post
    values:
      layout: sunday
